steps          : 'prepare_inputs,align_assemblies,generate_chains,liftover'
aligner        : 'blat'
tracing        : true
input          : './assembly_samplesheet.csv'
liftover_input : './beds_to_lift.csv'
